# Generated by Django 4.1 on 2022-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_mobile'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ManyToManyField(help_text='用户', to='users.userprofile', verbose_name='用户'),
        ),
    ]
