# Generated by Django 4.1 on 2022-09-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_examiner'),
        ('report', '0002_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='CRH',
            field=models.ForeignKey(help_text='考试车型', on_delete=django.db.models.deletion.CASCADE, to='users.crh', verbose_name='考试车型'),
        ),
        migrations.AlterField(
            model_name='report',
            name='count',
            field=models.IntegerField(default=0, verbose_name='补考次数'),
        ),
        migrations.AlterField(
            model_name='report',
            name='examiner',
            field=models.ForeignKey(help_text='考评人', on_delete=django.db.models.deletion.CASCADE, to='users.examiner', verbose_name='考评人'),
        ),
    ]
