# Generated by Django 4.1 on 2022-09-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_crh_alter_report_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='score',
            field=models.FloatField(verbose_name='考试成绩'),
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=600, null=True, verbose_name='扣分原因')),
                ('report', models.ForeignKey(blank=True, db_constraint=False, help_text='关联统计表', null=True, on_delete=django.db.models.deletion.PROTECT, to='report.report', verbose_name='关联统计表')),
            ],
            options={
                'verbose_name': '扣分原因',
                'verbose_name_plural': '扣分原因',
                'db_table': 'table_reason',
            },
        ),
    ]
