# Generated by Django 4.1 on 2022-09-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_examiner_name'),
        ('report', '0004_alter_report_score_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ('id',), 'verbose_name': '扣分原因', 'verbose_name_plural': '扣分原因'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('id',), 'verbose_name': '统计表', 'verbose_name_plural': '统计表'},
        ),
        migrations.AlterField(
            model_name='report',
            name='score',
            field=models.IntegerField(verbose_name='考试成绩'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ManyToManyField(help_text='考生', to='users.userprofile', verbose_name='考生'),
        ),
    ]
