# Generated by Django 4.1 on 2022-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reason_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='usetime',
            field=models.CharField(help_text='XX分XX秒', max_length=100, verbose_name='考试使用时间'),
        ),
    ]
