# Generated by Django 4.1 on 2022-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_usetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='points',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='扣分点'),
        ),
    ]
