# Generated by Django 4.1 on 2022-09-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='table_users',
        ),
        migrations.AlterModelTable(
            name='verifycode',
            table='table_verifycode',
        ),
    ]
