# Generated by Django 4.1 on 2022-09-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='车型资质', max_length=64, verbose_name='车型资质')),
                ('sort', models.IntegerField(default=1, help_text='车型顺序', verbose_name='车型顺序')),
            ],
            options={
                'verbose_name': '车型表',
                'verbose_name_plural': '车型表',
                'db_table': 'system_crh',
                'ordering': ('sort',),
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='post',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CRH',
            field=models.ManyToManyField(db_constraint=False, help_text='关联车型资质', to='users.crh', verbose_name='关联车型资质'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='post',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联岗位', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.post', verbose_name='关联岗位'),
        ),
    ]
