# Generated by Django 4.1 on 2022-09-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_crh_remove_post_code_remove_userprofile_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(0, '离职'), (1, '在职')], default=1, help_text='在职状态', verbose_name='在职状态'),
        ),
    ]
