# Generated by Django 4.1 on 2022-09-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_post_status_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_keypeople',
            field=models.BooleanField(default=False, help_text='是否为关键人', verbose_name='是否为关键人'),
        ),
    ]
