# Generated by Django 4.1 on 2022-09-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='考评表名称', max_length=100, verbose_name='考评表名称')),
                ('points', models.CharField(blank=True, max_length=100, null=True, verbose_name='扣分点')),
                ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='扣分原因')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '考评表',
                'verbose_name_plural': '考评表',
                'db_table': 'table_forms',
            },
        ),
    ]
