# Generated by Django 4.1 on 2022-09-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='points',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='reason',
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.CharField(blank=True, max_length=100, null=True, verbose_name='扣分点')),
                ('forms', models.ForeignKey(blank=True, db_constraint=False, help_text='关联考评表', null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.forms', verbose_name='关联考评表')),
            ],
        ),
    ]
