# Generated by Django 4.1 on 2022-09-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_remove_forms_points_remove_forms_reason_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': '扣分点', 'verbose_name_plural': '扣分点'},
        ),
        migrations.AlterModelTable(
            name='points',
            table='table_points',
        ),
    ]
