# Generated by Django 4.1 on 2022-09-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_points_options_alter_points_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='forms',
        ),
        migrations.AddField(
            model_name='forms',
            name='points',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联扣分点', null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.points', verbose_name='关联扣分点'),
        ),
    ]
