# Generated by Django 4.1 on 2022-09-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_points_forms_forms_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
