# Generated by Django 4.1 on 2022-09-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rename_point_points_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='points',
        ),
        migrations.AddField(
            model_name='points',
            name='forms',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联考评表', null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.forms', verbose_name='关联考评表'),
        ),
        migrations.AlterField(
            model_name='points',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
