# Generated by Django 4.1 on 2022-09-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_forms_points_points_forms_alter_points_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='name',
            field=models.CharField(help_text='考评表名称', max_length=400, verbose_name='考评表名称'),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='扣分点'),
        ),
    ]
