# Generated by Django 4.1 on 2022-09-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_forms_name_alter_points_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='扣分点'),
        ),
    ]
